public class scorecard {
    public static void main(String[] args) {
        // .29x  start till .111x
        System.out.println("__________________________________________________________________________________");
        System.out.println("|                                                                                |");
        System.out.println("|                                                                                |");
        System.out.println("|                                                                                |");
        System.out.println("|                      -----CRICKET WORLD CUP 2023-----                          |");
        System.out.println("| *Venue: Arun Jaitley Stadium, Delhi   *Date & Time: Oct 25, 02:00 PM LOCAL     |");
        System.out.println("|                                                                                |");
        System.out.println("|                                                                                |");
        System.out.println("|             <<<<<<<    AUSTRALIA Vs NETHERLANDS    >>>>>>>                     |");
        System.out.println("|                                                                                |");
        System.out.println("| *Toss ---> Australia won the toss and opt to bat                               |");
        System.out.println("|                                                                                |");
        System.out.println("|                                                                                |");
        System.out.println("| AUSTRALIA INNINGS                                          399-8 (50 Ov)       |");
        System.out.println("|                                                                                |");
        System.out.println("| Batter                                                     R  B  4s  6s SR     |");
        System.out.println("| 1. Mitchell Marsh   c Ackermann   b van Beek               9  15 2   0  60.00  |");
        System.out.println("| 2. Warner           c Aryan Dutt  b van Beek             104  93 11  3 111.83  |");
        System.out.println("| 3. Steven Smith     c van der Mer b Aryan Dutt            71  68  9  1 104.41  |");
        System.out.println("| 4. Labuschagne      c Aryan Dutt  b Bas de Leede          62  47  7  2 131.91  |");
        System.out.println("| 5. Josh Inglis (wk) c Sybrand En  b Bas de Leede          14  12  1  1 116.67  |");
        System.out.println("| 6. Maxwell          c Sybrand En  b van Beek             106  44  9  8 240.91  |");
        System.out.println("| 7. Green            run out (Sybrand Engelbrecht)          8  11  1  0  72.73  |");
        System.out.println("| 8. Cummins (c)      not out                               12   9  2  0 133.33  |");
        System.out.println("| 9. Starc            c Ackermann   b van Beek               0   1  0  0   0.00  |");
        System.out.println("|10. Zampa            not out                                1   1  0  0 100.00  |");
        System.out.println("|                                                                                |");
        System.out.println("| Extras                         12 (b 0, lb 0, w 11, nb 1, p 0)                 |");
        System.out.println("| Total                                                    399 (8 wkts, 50 Ov)   |");
        System.out.println("| Did not Bat         Hazlewood                                                  |");
        System.out.println("|                                                                                |");
        System.out.println("|* FALL OF WICKETS----                                                           |");
        System.out.println("| 28-1  (Mitchell Marsh, 3.5)                                                    |");
        System.out.println("| 160-2 (Steven Smith, 23.3)                                                     |");
        System.out.println("| 244-3 (Labuschagne, 36.1)                                                      |");
        System.out.println("| 266-4 (Josh Inglis 38.6)                                                       |");
        System.out.println("| 267-5 (Warner, 39.1)                                                           |");
        System.out.println("| 290-6 (Green, 42.2)                                                            |");
        System.out.println("| 393-7 (Maxwell, 49.3)                                                          |");
        System.out.println("| 393-8 (Starc, 49.4)                                                            |");
        System.out.println("|                                                                                |");
        System.out.println("|  Bowler                          O  M  R  W  NB  WD  ECO                       |");
        System.out.println("|1.Aryan Dutt                      7  0  59 1  0    0  8.40                      |");
        System.out.println("|2.Ackermann                       4  0  19 0  0    0  4.80                      |");
        System.out.println("|3.van Beek                       10  0  74 4  0    5  7.40                      |");
        System.out.println("|4.van Meekeren                   10  0  64 0  0    3  6.40                      |");
        System.out.println("|5.Vikramjit Singh                 4  0  27 0  0    1  6.80                      |");
        System.out.println("|6.van der Merwe                   5  0  41 0  0    1  8.20                      |");
        System.out.println("|7.Bas de Leede                   10  0 115 2  1    1 11.50                      |");
        System.out.println("|                                                                                |");
        System.out.println("|                                                                                |");
        System.out.println("|                                                                                |");
        System.out.println("|                                                                                |");
        System.out.println("| NETHERLANDS INNINGS                                        90-10 (21 Ov)       |");
        System.out.println("|                                                                                |");
        System.out.println("| Batter                                                     R  B  4s  6s SR     |");
        System.out.println("| 1. Vikramjit Singh  run out (Maxwell)                     25 25  6  0 100.00   |");
        System.out.println("| 2. Max ODowd                      b Starc                  6  9  1  0  66.67   |");
        System.out.println("| 3. Colin Ackermann  lbw b Hazlewood                       10 11  2  0  90.91   |");
        System.out.println("| 4. Sybrand Engelb   c Warner      b Mitchell Marsh        11 21  1  0  52.38   |");
        System.out.println("| 5. Bas de Leede     lbw           b Cummins                4  7  1  0  57.14   |");
        System.out.println("| 6. Scott (c & wk)   not out                               12 22  0  0  54.55   |");
        System.out.println("| 7. Teja Nidama      c Josh Inglis b Mitchell Marsh        14 18  2  0  77.78   |");
        System.out.println("| 8. Logan van Beek   c Josh Inglis b Zampa                  0  3  0  0   0.00   |");
        System.out.println("| 9. Roelof van der             lbw b Zampa                  0  1  0  0   0.00   |");
        System.out.println("|10. Aryan Dutt                 lbw b Zampa                  1  8  0  0  12.50   |");
        System.out.println("|11. Paul van Meek    st JoshInglis b Zampa                  0  1  0  0   0.00   |");
        System.out.println("|                                                                                |");
        System.out.println("| Extras                         7  (b 0, lb 0, w 7, nb 0, p 0)                  |");
        System.out.println("|                                                                                |");
        System.out.println("|                                                                                |");
        System.out.println("|                                                                                |");
        System.out.println("|                                                                                |");
        System.out.println("|* FALL OF WICKETS----                                                           |");
        System.out.println("|  28-1 (Max ODowd, 4.5)                                                         |");
        System.out.println("|  37-2 (Vikramjit Singh, 5.5)                                                   |");
        System.out.println("|  47-3 (Colin Ackermann, 9.2)                                                   |");
        System.out.println("|  53-4 (Bas de Leede,   10.5)                                                   |");
        System.out.println("|  62-5 (Sybrand Engelbrecht, 13.2)                                              |");
        System.out.println("|  84-6 (Teja Nidamanuru, 17.5)                                                  |");
        System.out.println("|  86-7 (Logan van Beek, 18.3)                                                   |");
        System.out.println("|  86-8 (Roelof van der Merwe, 18.4)                                             |");
        System.out.println("|  90-9 (Aryan Dutt, 20.5)                                                       |");
        System.out.println("| 90-10 (Paul van Meekeren, 20.6                                                 |");
        System.out.println("|                                                                                |");
        System.out.println("|                                                                                |");
        System.out.println("|  Bowler                          O  M  R  W  NB  WD  ECO                       |");
        System.out.println("|1.Mitchell Starc                  4  0  22 1  0    2  5.50                      |");
        System.out.println("|2.Josh Hazlewood                  6  0  27 1  0    2  4.50                      |");
        System.out.println("|3.Pat Cummins (c)                 4  0  14 1  0    0  3.50                      |");
        System.out.println("|5.Adam Zampa                      3  0   8 4  0    0  2.70                      |");
        System.out.println("|                                                                                |");
        System.out.println("|                                                                                |");
        System.out.println("|                        ---AUSTRALIA WON BY 309 RUNS---                         |");
        System.out.println("|                                                                                |");
        System.out.println("| AUSTRALIA SQUAD                     |              NETHERLAND'S SQUAD          |");
        System.out.println("| 1.WARNER                            |              1.VIKRAMJIT SINGH           |");
        System.out.println("| 2.MITCHELL MARSH                    |              2.MAX DWOD                  |");
        System.out.println("| 3.STEVEN SMITH                      |              3.ACKERMANN                 |");
        System.out.println("| 4.LABUSCHAGNE                       |              4.BAS DE LEEDE              |");
        System.out.println("| 5.MAXWELL                           |              5.TEJA NIDAMANURU           |");
        System.out.println("| 6.GREEM                             |              6.EDWARDS(C & wk)           |");
        System.out.println("| 7.CUMMINS(C)                        |              7.SYBRAND ENGELBR.          |");
        System.out.println("| 8.STARC                             |              8.VAN BEEK                  |");
        System.out.println("| 9.HAZLEWOOD                         |              9.VAN DER MERWE             |");
        System.out.println("|10.ZAMPA                             |             10.ARYAN DUTT                |");
        System.out.println("|11.JOSH INGLIS(wk)                   |             11.VAN MEEKEREN              |");
        System.out.println("|                                                                                |");
        System.out.println("|                                                                                |");
        System.out.println("|________________________________________________________________________________|");
    }
}
